{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "cd1f1a64-c281-439c-80c9-9feb98519e2f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🏥 Dataset loaded successfully via pandas!\n",
      "Dataset Dimensions: 4240 rows, 16 columns\n",
      "\n",
      "--- Step 1: Preprocessing Data ---\n",
      "✅ Clinical missing values handled and features scaled accurately.\n",
      "\n",
      "--- Step 2: Executing Train-Test Split ---\n",
      "Training Data Split Shape: (3392, 15)\n",
      "Testing Data Split Shape:  (848, 15)\n",
      "\n",
      "--- Step 3: Initializing & Fitting Machine Learning Model ---\n",
      "🎯 Model training completed successfully via model.fit()!\n",
      "\n",
      "--- Step 4: Model Evaluation ---\n",
      "====================================================\n",
      "            ASSIGNMENT EVALUATION REPORT            \n",
      "====================================================\n",
      "🟢 Final Model Accuracy Score: 0.6722 (67.22%)\n",
      "\n",
      "Detailed Classification Matrix Profile:\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "         0.0       0.90      0.69      0.78       719\n",
      "         1.0       0.25      0.60      0.36       129\n",
      "\n",
      "    accuracy                           0.67       848\n",
      "   macro avg       0.58      0.64      0.57       848\n",
      "weighted avg       0.81      0.67      0.72       848\n",
      "\n",
      "====================================================\n",
      "\n",
      "--- Step 5: Generating Performance Visualizations ---\n",
      "💾 Heatmap chart saved successfully as 'visualization_screenshot.png'!\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXUAAAFgCAYAAABE5ungAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjkuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8ekN5oAAAACXBIWXMAAAsTAAALEwEAmpwYAAArNUlEQVR4nO3dd7wdVbn/8c83nUAoIQEJARJK6BgkiNJuKKJCJIC0XPGKohCvUn+AYAFULhfLBRFEpGiIFJUWKVIEgYQugQABAtKkS4ckppDk+f2x1k52TvbZZ87JKTvD9/167deeWdOe2WefZ9asmT1LEYGZmZVDt64OwMzM2o+TuplZiTipm5mViJO6mVmJOKmbmZWIk7qZWYk4qZeUpCGSQlJUlUV+DSm4jpF5/hfaKaYX8vpGtsf6liKOFSX9WdL0HM+322GdrfpslzW1vk/L4jaabG+x73dnb7+jOKkvwyRtJ+k6SW9Lmi3pWUlnS+rVzCJn5dcHBTfxcp7/t+0RbxGSVpV0Zt6XOZLekHSDpE+042bGAnsCbwO/BKa0wzpb+9m2mqQ7qg4eB1WVryNpfmsTkqRxeZlTCsz+AYv2sbVxq+qAfnCTafvl8n8B/27rNtpJm/exkfTo6gCsbSQdCFwCdAceAf4ODCElrB/UWiYijmrNNiLiGaBVyywNSasB9wFDgXeAK0nf0R3z66F22tSw/D4+Ik5qjxW29rNtB2NJf3+AQ+nACpqknhHxDm38LkRESLoMOBEYA4yrmvyf+f0PEfFGW7fRHpZmH4vIn+OHHbX+hSLCr2XsBfQl1TID+D3QrWraekAvUoKP9CdeOC3ya0gefyGPnwA8DMwE/gKskqePzNNfqFrHxsA1wKvALFItd5087TLgFWAOMB34G7B51bKV7Y1sZr/Oy9PfANasKu8DDM3DywM/A54FZuTtf7lq3lPyOq4Exud5ngF2zdPHVX0OlddI4I48fHCtfc+f6QXA63n/XgKuq/PZDgQuBF4k1QDvAz5XNX8ljvOA60i11EeB4XX+7pUY38nvmwM9c0yVsuq/9//lz3x2Xv99lc++mc9hHFXfG9KB41Xgdpp8n4Av5fFHcgwb5G1MB9arEfsmef55wGq5bOUcWwAjamxDwGn5s56T9/NmYNVmPvNTKvuRx7fI+/wu8CHwGnAO0KuZv3HT7R9c4zOq/o6sDfyB9J1/D7gF2KzG9/17wOPA/M7ID25+WTZtB/TPw6dGxILKhIh4NiLmtnJ9J5ESymzg88AxtWaS9DFgErAX6R/sEtI/3ip5lnVIiedCUq16J+BPrYjjC/n9ooh4pVIYEbMj4vk8+jvgWGB+XvcGwHhJY5qs64vAIGAq6UBXaUK6BXgyD99POtV+uUBs/wV8HXgLuAiYDGxba0ZJ3YBrgUPy/H8GtgJukNR0mcNIie55UpI+u0AsvwcWAN8E9gFWZ/Hab8VQ0j5eRErM2wBXSOpH7c/hlibL/w9wI3BP0xVHxKXAFaTEeQLpb74ccExEPFtj/idIFYfuwH65+ItAb2BaRDxYI/5dSLX7+XkfJpI+o3415q1lIDAXuIr0958PfItmvt81PMGi5pgrq8pfk9SXVGnZn/S/cy3pIPE3SQOarOeHwGPA1QW3u3S6utbpV+tfLKolBdCnmXmGwBI1t+Zq6sfl8R/m8evz+EgWr8kcm8cfYvGzgx75fU3gcOB0UnKqbG9Qk+2NbCbmD/P0sc1MX61qnevksiPz+D15/JQ8PpV0wBlatcyAPM+4PH5K1brvoH5N/Zt5/HLSQXUVoHutzxb4ZB6eDiyfp5+Zyy5rEsMNeXynPD6jzt+9EuNRpDOqyhnA28Cnavy9+5OaZk4DfkE6Ewtg2zqfw5Cqfdm5he9Tf1ItdQFV35s68R+T57srj9+ax79XaxukCkbk+Ubmv7/I373qz7zJ335c1TZ3JB0YzgBuy9NvaeZvvMQ+5vIVSWckAfw4l+2Xx1/On+0vSGeEC7+/LPq+/6gz84Pb1JdNb1QNrwM8tZTrezi/v5ffV2hmvqH5/e+x+NnBPEkbkJJ9rWUHkk7jW/IGqXa9TjPTh+T3WRHxzzw8Lb83XWZKRISk96rKViDVnIvo3mR8PCkJjAYOJCcbSXtHxMxm4nypalpzcTb97JcvGN+vSUlvG1Izy+zqiZJWJdUgB9VYdmDBbdxdb2JEvCPpQtKZHjmOei4HfgpsK2kbFh3ILm1m/luAc4Evk840AB4kXeR+rcb8i/3NJJ1IOqA1VXT/kdSTVMPegnSwqFyvGpLf1yRVLKqt32S87ufY3tz8smy6h9ROCPD9fLoPLLwTomcr1zcvv0cL81WaQLZuss0ewB6kpDmF1Fa6etVyKhjH9fn9EElrVq2/l6S1STUfgOXyOMCG+b2S5CuK7lNFJfmumN83a7q+iDggT9+YVHv8DKn5o6lKnGvl0/T2jLPiBlJ7fZDa5ZvagZTQXwc+RmrmeC9Pq/w95uf3mnkgIubUC0DSUOBoFh1Qzqj33YuI10hNFiI13XUj1dpfaGaR7sC3Sd+n9UkH1hGkZjBIbfjQ/N/sgPz+fdIF9+9UQq+zWwtJEqnZZhfgJuAbVZMrMU8mnTkoIipNkf/TZFV1P8f25pr6MigiZko6nPQlPwjYXNIDpH/iz7B4Qm1Pl5DaT7cEHpA0mdRW/HXgX3meYaQ2yOFtWP/JwGdJtdlHJd1I+gfcATgjIn4h6UpgX+Cvku4mtWlCugC2NB4GdgeOyQeMrzeZPkbSd0g1xRmktl1YlCirPUhqp94GmCTpcdJdH0GqeS61iFggaXdg5Yh4RtLwJrNU/h4DSU0P67HkWdRL+f0gSSsBE1h04K4rH9THk9q3vw7sRvpb/BD4bp1FLyF9R9evGm/OtqQmontJF4K3y+Xv5feHc9k5kp4inUVVq3wGX8rb26vOtmo5lPT/FaRmpp+nPM9lpOav50nf/7slPUq6cDqS9D26o5XbajeuqS+jIl2o2on05Vob+AqpBnkBi2ow7b3N10kJdgLptPO/SBWDd0kXLS8i1f52Bf63jevfmnTv+PukJPEZUvv4xDzb10jt071INbHngK9GxGVt3K2KM0i1sQGkz/XMJtOfIjXd7E66ADoXOJVFZxfV+7GA1ETwO1I78N6kBLRnRNy1lHFWb+fxiKh5ah8R95JqjB+QEu7lpMRU7QLSWd+awBGkBFXUccD2wF8j4iLSBcg3gONrXAyudjWLvp9zSBdbm/MK8A9STfkbpLu+zgPOz9MPJ12AHA4MJn3e1Y4m1aTXJR3UziiwX9XWyO8i/c2PzK9NcrPazqTPtfL/tyHpILW0zaFLRblB38zMSsA1dTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEvHz1DuJeiwX6lW0a0X7qFpr7Y91dQi2DHj79ZeZ8d47NTv7cFLvJOrVj94b7t/yjPaR9p1fHdvVIdgy4Cdf27PZaW5+MTMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MysRJ3UzsxJxUjczKxEndTOzEnFSNzMrESd1M7MScVI3MyuRHl0dgJVbt27i9vHH89ob73PgMeexw4hh/PjIvenVsztTnnyJw0+9lPnzF/D5HTfne2NHsSCCefMW8N0zruS+R57r6vCtE7z77gdcfvGNzJg+ExCf2n4LdtxpK667+g4en/ocPbp3Y9WBK3PgQZ9jub59AHj1lTe58vJbmD1rLuomjjr+IHr2dDqDLkjqkmZExApV4wcDIyLi221Y10jg2IgYlYfnRsQ9edo44PqIuLKNca4BXBARo/L4icAhwHzgiIi4WVIv4FZg54iY15btlN3YA3fi6ef/Rb/l+yCJX5/yZUb/99k8++IbnHjYHozZYxsuufZeJv79KW6c+BgAm64/iN/+79fYZr9Tuzh66wzdu3Vjz31GMnjt1Zk9ey5n/uT3DNtoHYZtPITdR+9I9+7duH7Cndx2y/2M2us/mD9/AZeNu4H//MruDBq8GjNnzKJ7dzc6VJTpkxgJbNuO6zsGuABA0ibAgcCmwOeAcyV1j4i5wG3AAe243dIYtNrK7Lb9poz/8z0A9F9peeZ+OI9nX3wDgDvun8aeOw8HYOasuQuX67tcbyI6PVzrIiuutAKD114dgD59erH66v15/70ZbLjxkIXJep0hg3jv3RkAPP3kC6yx5kAGDV4NgOVXWI5u3cqUypZOQ30SkgZKukrS3/Nru1z+SUn3SnpY0j2SNmyy3BBgLHC0pCmSdsiTdszzPydp3zzveEl7VS17qaTRNcL5InBTHh4N/CEi5kTE88AzwCfztAnAl9pj/8vmtGO+yMm/nMCCBSlDv/3eDHp0787wjdcGYM9dhrPm6qssnH+PkVtw/xXf549njuXwH1/aJTFb13rn7fd55eU3WGfIGouVP3DvY2y86VAA3nzjXYT4zTlXcsbp4/nbXx/oilAbVlck9eVy4p0iaQrwo6ppZwFnRsTWpKR6YS6fBuwQEVsCJwGnVa8wIl4AzsvLDo+ISXnSGsD2wCjg9Fx2EXAwgKSVSLX7G6rXJ2ko8G5EzMlFawIvVc3yci4DmAps3Yr9/0j47Pab8da703lk2kuLlR/yvd9x2tH7cOu4Y5kxcw7zFyxYOO2GOx5lm/1O5aDjzue7Y/fo7JCti82ZPZeLL7iW0fvuRJ/lei8sv/Wm++jWvRuf2HpjAOYvWMDzz73Mlw7enW8fM4apj/yDp6f9s6vCbjhdcWVhVkQMr4xU2tTz6K7AJpIqk1eUtAKwEnCxpA2AAHoW3NaEiFgAPCFpdYCIuFPSuZIGkg4cV9VoD18DeLPIBiJivqS5kvpFxPTqaZIOBQ4FoOcKtRYvrW0+vi6f22FzPrPtpvTu3ZN+y/fhNz/6Lw47aTy7H/oLAHbaZiPWW3u1JZa95+FnGbLmAPqvtDzvvD+zkyO3rjB//nzGXXgtn9h6Y7YYPmxh+QP3TuWJqc8y9oj9qeSFlVfux7rrD2aFFfoCsPGm6/LKS/9i2EbrdEnsjaahml9I8Xwq17aHR8SaETED+DFwe0RsBnwB6FNwfXOqhlU1PB44CPgq8Nsay81qso1XgLWqxgfnsorewOymK4mI8yNiRESMUI/lCoZcDj/61bVsNuoHfHz0yRzy3d8x6e9Pc9hJ4xmwSjq49erZgyO/8hl+d/VdAAwdPGDhsltsOJhePXs4oX9ERAR/vORmVv9Yf/5jlxELy6c9/jx33PoAXztsb3r1WlSP23CTIbz26lvMnfsh8+cv4Nl/vMTqa6zaFaE3pEa7B+gW4HDgZwCShkfEFFJNvZJED25m2enAigW3Mw54AHg9Ip6oMf1pYEjV+LXAZZLOAAYBG+TlkbQq8FZEfFhw2x9pR3x5V3bbfjO6dRO/vWoSkx58GoA9dx7OAXtsw7x585k1+0MO+W6tY62V0fPPvsLkB55gjUED+L/TLgZg9z134Jor/sa8efP5zdlXALDO0EHsO+Yz9O3bh//YeQS/+MklSLDRpuuyyWbrdeUuNBRFC7cZSLotInZpqazwBuvc0ihpAPArYGPSAWdiRIyV9GngYmAmqf37oIgY0uSWxmHAlcAC0oHhEKpuaayx3ZtIzTPnNbffwGER8Uwe/x7wNWAecFRE3JjL9wU+HRH/r95+d+u7WvTecP/WfFT2EfR/vzq2q0OwZcBPvrYn/5z2qGpNazapS+oD9AVuJ90uWFnBisBNEbFR+4faOST1BR4DPhER7zczz97AVhHx/RbWdTVwQkQ8XW8+J3UrwkndiqiX1Os1vxwGHEVqbpjMoqT+AXBOewbYmSTtSroD5szmEjpARFyTm1bqrasXqbZfN6GbmXWWZpN6RJwFnCXp8Ig4uxNj6lARcStQ6DJ5RFzYwvS5pIuuZmYNocULpRFxtqRtSRcOe1SVO5mZmTWYFpO6pN8D6wFTSM89gXSvuJO6mVmDKXJL4whgk2jpNhkzM+tyRX58NBX4WEcHYmZmS69ITX0A6Wf2D1D1C82I2LPDojIzszYpktRP6eggzMysfRS5++VOSesAG0TErfmHO907PjQzM2utFtvUJX2D9PP73+SiNUnPEDczswZT5ELpt4DtSL8kJSL+ASz5vFQzM+tyRZL6nPzLSQAk9SDdp25mZg2mSFK/U9J3ST0WfQa4AriuY8MyM7O2KJLUTyD1AvQY6SFffwHqPrnQzMy6RpG7XxYAF+SXmZk1sCJ3v4yS9LCkdyR9IGm6pA86IzgzM2udIj8++gWwD/CYn/9iZtbYirSpvwRMdUI3M2t8RWrqxwN/kXQniz/75YwOi8rMzNqkSFL/H2AG0Afo1bHhmJnZ0iiS1AdFxGYdHomZmS21Im3qf5G0W4dHYmZmS61IUv8mcJOkWb6l0cyssRX58VG/zgjEzMyWXpEfH20nafk8fJCkMySt3fGhmZlZaxVpfvk18G9JHwf+H/As8PsOjcrMzNqkSFKfl394NBo4JyJ+BbhJxsysARW5pXG6pBOBg4AdJXUDenZsWGZm1hZFauoHkH5JekhEvA4MBn7WoVGZmVmbFKqpA2dFxHxJw4CNgMs7NiwzM2uLIjX1iUBvSWsCtwBfBsZ1ZFBmZtY2RZK6IuLfpMfvnhsR+wF+bICZWQMqlNQlfRr4EnBDK5YzM7NOViQ5HwWcCFwTEY9LWhe4vUOjMjOzNinymIA7gTsl9c3jzwFHdHRgZmbWekUeE/BpSU8A0/L4xyWd2+GRmZlZqxVpfvkF8FngbYCIeATYsQNjMjOzNip0wTMiXmpSNL8DYjEzs6VU5MdHL0naFghJPYEjgSc7NiwzM2uLIjX1scC3gDWBV4DhedzMzBpMkbtf3iLdo25mZg2uyN0vP5W0oqSekm6T9KakgzojODMza50izS+7RcQHwCjgBWB94LiODMrMzNqmSFKvNNHsAVwREe93YDxmZrYUitz9cr2kacAs4JuSBgKzOzYsMzNrixZr6hFxArAtMCIiPgRmkrq2MzOzBlPkQul+wIe5k4zvA5cAgzo8MjMza7Uibeo/iIjpkrYHdgUuAn7dsWGZmVlbFEnqlUcC7AGcHxE3AL06LiQzM2urIkn9FUm/IXVA/RdJvQsuZ2ZmnaxIct4fuBn4bES8B/QHju3IoMzMrG2K3P3y74i4OiL+IWl5Urv6UR0emZmZtVqRu196Sdpb0hXAa8DOwHkdHpmZmbVasz8+krQbMAbYjdQn6Xhg64j4aifFZmZmrVSvpn4TsC6wfUQcFBHXAQs6JywzM2uLeo8J+ARwIHCrpOeAPwDdOyUqMzNrk2Zr6hExJSJOiIj1gJNJnWP0lHSjpEM7K0AzMyuuaB+l90TE4cBg4EzgUx0alZmZtUmRpzQuFBELgFvyy8zMGox/GWpmViJO6mZmJVLvPvX+9RaMiHfaPxwzM1sa9drUJwMBqMa0IN3DbmZmDaTZpB4RQzszkLLbcuO1ufv+c7o6DGtwM2fP6+oQbBlwft+ezU4rdPeLpFWADYA+lbKImLjUkZmZWbtqMalL+jpwJOke9Smke9TvJT3Yy8zMGkiRu1+OBLYG/hkROwFbAu91ZFBmZtY2RZL67IiYDSCpd0RMAzbs2LDMzKwtirSpvyxpZWAC8FdJ7wL/7MigzMysbVpM6hGxdx48RdLtwEqkx/KamVmDKdLz0ack9QOIiDuBO0jt6mZm1mCKtKn/GphRNT4jl5mZWYMpktQVEVEZyU9qbNXTHc3MrHMUSerPSTpCUs/8OhJ4rqMDMzOz1iuS1McC2wKvAC8D2wDu+cjMrAEVufvlDVJfpWZm1uDqPXr3+Ij4qaSzSU9lXExEHNGhkZmZWavVq6k/md8f7IxAzMxs6dV79O51+f3izgvHzMyWRpGnNA4DjgWGVM8fEX5Ko5lZgylyv/kVwHnAhcD8jg3HzMyWRpGkPi8i/AtSM7NlQJH71K+T9N+S1pDUv/Lq8MjMzKzVitTUv5Lfj6sqc8fTZmYNqMiPj9wBtZnZMqLej492joi/Sdqn1vSIuLrjwjIzs7aoV1P/D+BvwBdqTAvASd3MrMHU+/HRyfn9q50XjpmZLY16zS/H1FswIs5o/3DMzGxp1Gt+6ddpUZiZWbuo1/zyw84MxMzMll6zPz6S9DNJh9UoP0zS6R0blpmZtUW9X5TuDJxfo/wCYFTHhGNmZkujXlLvXd3hdEXueFodF5KZmbVVvaQ+S9IGTQtz2ayOC8nMzNqq3t0vJwE3SjoVmJzLRgAnAkd1cFxmZtYG9e5+uVHSXqQHeR2ei6cCX4yIxzohNjMza6W6D/SKiKksekqjmZk1uCLPUzczs2WEk7qZWYk4qZuZlUi9B3qdTXrEbk0RcUSHRGRmZm1W70Lpg50WhZmZtYt6tzRe3JmBmJnZ0muxj1JJA4HvAJsAfSrlEbFzB8ZlZmZtUORC6aXAk8BQ4IfAC8DfOzAmMzNroyJJfdWIuAj4MCLujIivkZ7gaGZmDabF5hfgw/z+mqQ9gFeB/h0XkpmZtVWRpH6qpJWA/wecDawIHN2hUZmZWZu0mNQj4vo8+D6wU8eGY2ZmS6PI3S+/o8aPkHLbupmZNZAizS/XVw33AfYmtaubmVmDKdL8clX1uKTLgbs6LCIzM2uztjzQawNgtfYOxMzMll6RNvXpLN6m/jrpF6ZmZtZgijS/9OuMQMzMbOm12Pwi6bYiZWZm1vXqPU+9D9AXGCBpFUB50orAmp0Qm5mZtVK95pfDgKOAQcBkFiX1D4BzOjYsMzNri3rPUz8LOEvS4RFxdifGZGZmbVTklsYFklaujEhaRdJ/d1xIZmbWVkWS+jci4r3KSES8C3yjwyIyM7M2K5LUu0uqtKcjqTvQq+NCMjOztiry7JebgD9K+k0ePyyXmZlZgymS1L8DHAp8M4//FbigwyIyM7M2a7H5JSIWRMR5EbFvROwLPEHqLMPMzBpMkZo6krYExgD7A88DV3dkUGZm1jb1flE6jJTIxwBvAX8EFBHu/cjMrEHVq6lPAyYBoyLiGQBJ7pvU2myLPU9ihb696d6tGz16dOP28d/hB2ddw82TptKzZ3eGDh7Ar046iJX69e3qUK2LPPviv/jmyRcvHH/x1bc59pDPM/nxF3j2xTcA+GDGLFZcYTlu+d3xXRVmQ6uX1PcBDgRul3QT8AcWPSrArE2uO+9IVl15hYXjO22zESd/a0969OjOyWdP4Ixxt/DDw/fqugCtS6239uoLk/X8+QsYsc/JfG7HLfj6/iMXzvOjcybQb/k+XRRh42v2QmlETIiIA4GNgNtJz4FZTdKvJe3WnkFI2ktSSNqoqmy4pN2bmX+kpPclTZE0TdLPq6btKemEOts6WFKLz67JMZ2Uh3eU9JCkeZL2rZpnYD7gWRvt/KmN6dGjOwBbbzaUV//1XtcGZA3jrslPs86gAQz+WP+FZRHBdbdPYfSuW3VhZI2tyN0vMyPisoj4AjAYeJj27yRjDKmLvDFVZcOBmkk9mxQRw4EtgVGStsvxXhsRp7dDTMcD5+bhF4GDgcuqZ4iIN4HXKtu2+iSxz7fPYeSXf8K4q5fsEfGSa+9l12036YLIrBFde9tDjN71E4uV3f/IcwxcpR/rrjWwi6JqfK3qzi4i3o2I8yNil/YKQNIKwPbAIaTmHiT1An4EHJBr4wfUiWkWMIX8OODqmrik/SRNlfSIpIk1tr2HpHslDWhSPgyYExFv5W28EBGPAgtqhDAB+FIrd/sj6cYLjubOS07girP+mwuvnMTdDz2zcNrPf3sTPXp0Y//Pb92FEVqjmPvhPG65+3FG7TR8sfI/3zp5iURvi2tLH6XtbTRwU0Q8DbwtaauImAucBPwxIoZHxB+bWzg/630DYImkndfx2Yj4OLBnk+X2Bk4Adq8k7yrbAQ8VjP9BYIdmYjtU0oOSHnzzrTcLrq68Bq22MgAD+/dj1MgteOjxFwC47Lr7uOWuqZz/44OpeiKFfYTdft+TbD5sMAP7L+p4bd68+dw48VG+sPOWXRhZ42uEpD6GdBGW/D6mzrzVdpD0CPAKcHNEvF5jnruBcZK+AXSvKt+Z1IS0R35AWVNrAEWz8BukZ84vIZ/VjIiIEQMHfLRPF2fOmsP0mbMXDv/tvmlsvN4gbr3nCX75+1u57P8Oo28fP1LIkj/f+hCjd1m8Rj5p8tOst/bqCysHVluhHx91FEn9SQl2c0lBSrwh6bgCi0+KiFGShgL3SfpTREypniEixkraBtgDmCypcnXlWWBdYBippt3ULGClgrvRJ89vdbz59nQOOj49XWL+vPl88XMj2HXbTfjE3qcwZ+489v5WunY9YvMhnHli0eO6ldG/Z81h4oNPcfpx+y9Wfu2tD7GXm15a1KVJHdgX+H1EHFYpkHQnqTljOtBip9cR8byk00k178WygaT1IuJ+4H5JnwfWypP+CRwHXC1pv4h4vMlqnwQOKrgPw4CpBef9yBoyeAB3XXbiEuUPXXNK5wdjDa3vcr2ZesNpS5Sf+T1fuiqiq5tfxgDXNCm7KpffDmzS0oXS7DxgR0lDmpT/TNJjkqYC9wCPVCZExDTSBc4rJK3XZLmJwJaVRw5L2lrSy8B+wG8kVR8EdgJuaCE+M7NOoYjo6hgakqSzgOsi4tYW5psIjG6mbX6hrbYaEXffX6ulx2yRmbPndXUItgzYZcdtmPLQ5Jp3FXR1Tb2RnQbU/b26pIHAGS0ldDOzztLVbeoNKyL+BVzbwjxvku5TNzNrCK6pm5mViJO6mVmJOKmbmZWIk7qZWYk4qZuZlYiTuplZiTipm5mViJO6mVmJOKmbmZWIk7qZWYk4qZuZlYiTuplZiTipm5mViJO6mVmJOKmbmZWIk7qZWYk4qZuZlYiTuplZiTipm5mViJO6mVmJOKmbmZWIk7qZWYk4qZuZlYiTuplZiTipm5mViJO6mVmJOKmbmZWIk7qZWYk4qZuZlYiTuplZiTipm5mViJO6mVmJOKmbmZWIk7qZWYk4qZuZlYiTuplZiTipm5mViJO6mVmJOKmbmZWIk7qZWYk4qZuZlYiTuplZiTipm5mViJO6mVmJOKmbmZWIk7qZWYk4qZuZlYiTuplZiTipm5mViJO6mVmJOKmbmZWIk7qZWYk4qZuZlYiTuplZiTipm5mViJO6mVmJOKmbmZWIk7qZWYk4qZuZlYiTuplZiTipm5mViCKiq2P4SJD0JvDPro6jwQwA3urqIKzh+XuypHUiYmCtCU7q1mUkPRgRI7o6Dmts/p60jptfzMxKxEndzKxEnNStK53f1QHYMsHfk1Zwm7qZWYm4pm5mViJO6mZmJeKkbouRNKPJ+MGSzmnjukZKur5qeNuqaeMk7bsUca5RWXceP1HSM5KekvTZXNZL0kRJPdq6HStG0l6SQtJGVWXDJe3ezPwjJb0vaYqkaZJ+XjVtT0kn1NlWoe9kjumkPLyjpIckzav+3kkaKOmmovu5LHBSt84yEti2pZla4RjgAgBJmwAHApsCnwPOldQ9IuYCtwEHtON2rbYxwF35vWI4UDOpZ5MiYjiwJTBK0nYAEXFtRJzeDjEdD5ybh18EDgYuq54hIt4EXqtsuwyc1K2wXKu5StLf82u7XP5JSfdKeljSPZI2bLLcEGAscHSume2QJ+2Y53+uUnuSNF7SXlXLXippdI1wvghUalijgT9ExJyIeB54BvhknjYB+FJ77L/VJmkFYHvgENLBFUm9gB8BB+S/ebMH1oiYBUwB1szLLqyJS9pP0lRJj0iaWGPbe+Tv3oAm5cOAORHxVt7GCxHxKLCgRggTKNF3xKel1tRykqZUjfcHrs3DZwFnRsRdktYGbgY2BqYBO0TEPEm7AqeRki6Q/qEknQfMiIifA0g6BFiDlAw2ytu4ErgIOBqYIGklUu3+K9UBShoKvBsRc3LRmsB9VbO8nMsApgJbt/GzsGJGAzdFxNOS3pa0VURMzk0fIyLi2/UWlrQKsAGwRNIGTgI+GxGvSFq5yXJ7k87Ydo+Id5sstx3wUMH4HwROLThvw3NSt6Zm5VNiINWagMpPtHcFNpFUmbxirqWtBFwsaQMggJ4FtzUhIhYAT0haHSAi7pR0rqSBpAPDVRExr8lyawBvFtlARMyXNFdSv4iYXjAua50xpAM+wB/y+OQCy+0g6RFSQv9FRLxeY567gXGS/gRcXVW+M+l7uVtEfFBjucLfEeANYFDBeRuek7q1RjfgUxExu7ownyrfHhF756aWOwqub07VsKqGxwMHkU7lv1pjuVlAn6rxV4C1qsYH57KK3sBiMVv7kNSflGA3lxRAdyAkHVdg8UkRMSqfed0n6U8RMaV6hogYK2kbYA9gsqSt8qRngXWBYaSadlOzSJWNIvrk+UvBberWGrcAh1dGJA3PgyuxKIke3Myy04F+BbczDjgKICKeqDH9aWBI1fi1wIGSeucEsQHwQI5xVeCtiPiw4LatdfYFfh8R60TEkIhYC3ge2IGCf/N8HeR04DtNp0laLyLuj4iTSDXvysH7n6QzufGSNq2x2ieB9QvuwzBSM10pOKlbaxwBjJD0qKQnSBc/AX4K/K+kh2n+7O86YO8mF0prioh/kf4pf9fM9JnAs5LWz+OPA38CniBdPP1WRMzPs+8E3FB0B63VxgDXNCm7KpffTmquq3uhNDuPdOF8SJPyn0l6TNJU4B7gkcqEiJhGusB5haT1miw3EdhSua1Q0taSXgb2A34j6fGqeUv1HfFjAqzhSOoLPAZ8IiLeb2aevYGtIuL7LazrauCEiHi6/SO1RibpLOC6iLi1hfkmAqNrXGxdJrmmbg0l3z3zJHB2cwkdICKuAV5oYV29SBdjndA/mk4D+tabIV+QP6MsCR1cUzczKxXX1M3MSsRJ3cysRJzUzcxKxEndzKxEnNTNzErESd3MrESc1M3MSsRJ3cysRJzUzcxKxEnduoyk+flhT1MlXZGf+dLWdS3s81TShbmLu+bmXay/1FZs44WmPexUlU9qUjYlP4SqNesvvA911rGwX9ga5e/n3qmeUuq7dVTV9LGS/qu122tPjRBDGfh56taVFnbIIelS0lMfz6hMlNSjRgcZLYqIr7cwy0hgBumpf+2ln6S1IuIlSRsv7coK7ENbTIqIUbDwsckTJM2KiNsi4rwO2F6rNEIMZeCaujWKScD6uUY5SdK1pB6Rukv6mVKfqI9KOgxAyTm51nkrsFplRZLukDQiD39OqRf5RyTdphr9par5vldXlXSLpMclXcjiHXk09ScWdXA9Bri8Kp523YdcVrdf2Jbkzih+BHw7r+8UScfm4W/kWB/Jn0vfXL6epPvyo3BPlTQjl4/M8V4paZpSv7KVR97ukmN8TNJvJfXO5adLeiJ/Hj+vEcMRVdP/0Jp9+8iLCL/86pIXqc9SSGeMfwa+SapFzwSG5mmHAt/Pw71JvdwMBfYB/krqaWcQ8B6wb57vDlJXZwOBl6rW1T+/nwIcWxXHZcD2eXht4Mk8/EvgpDy8B6mrvgE19uMFYEPgnjz+MLAJMLUD92FFoEce3pXU7R/587u+RoxLlAPDq/Z14WcCrFo1z6nA4Xn4emBMHh5b9fcbCbxP6nGqG3Avqe/ZPjn2YXm+8aTOT1YFnmLRAwVXrhHDq0Dv6ul+FXu5+cW6UnUn15NInU5vCzwQqTccgN2ALSptzaReljYAdgQuj9QZxquS/lZj/Z8CJlbWFRHvNBNHc32v7khKvETEDZLqPZ71beBdSQeSHh3876ppHbEPbe0XtlpzZx6bSToVWBlYgdTBOMCngb3y8GXAz6uWeSAiXoZ0PYHUM9V04PlY9Ojji4FvAeeQuhe8KLf/L3ENAHgUuFTSBGBCq/bqI85J3brSYp1cA+TEOrO6iFRTvLnJfLu3YxzN9b3a2vX8EfgVS3bp1xH78GPa1i9stS1JB6CmxgF7RcQjSh2Pjyywrur+ZudTJ7dExDxJnwR2IXWH921SP6fV9iAd9L4AfE/S5tGG6ysfRW5Tt0Z3M/BNST0BJA2TtDypu7IDcnv1GqQuyZq6j9RF2tC8bP9c3rTvzOb6Xp0I/Gcu+zywSguxXkPq2u/mJuUdsQ9F+oVtlqQtgB+QDkJN9QNey/F+qUksX8zDBxbYzFPAEOVuB4EvA3fms6CVIuIvwNHAx5vE1g1YKyJuJ/VbuhLpjMEKcE3dGt2FpFP5h/LFtzdJTQDXkGp3TwAvktpxFxMRb0o6FLg6J4o3gM+Q+ku9UtJoUjI/AviVpEdJ/xMTSW3GPwQuV+rP8p68nWZFxHTgJ7BELb8j9uGnpOaX71O8f80dlPqR7ZvXc0RE3FZjvh8A9+c472fRAfAo4BJJ3yP1Bdtsz1Q59tmSvkrqQ7QH8HdSX6T9gT9L6kM6izmmyaLd83ZWytN/GRHvFdzHjzz3fGRmheS7YGZFRORrB2MiYnRXx2WLc03dzIraCjgnn228B3yta8OxWlxTNzMrEV8oNTMrESd1M7MScVI3MysRJ3UzsxJxUjczK5H/D8vLVNtzCWuXAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x360 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "# ==============================================================================\n",
    "# Course: Applied Machine Learning for Clinical Insight\n",
    "# Project Title: Healthcare Disease Prediction System (10-Year CVD Predictor)\n",
    "# Author Name: [Insert Your Full Name Here]\n",
    "# Total Marks: 20 Assignment Submission\n",
    "# ==============================================================================\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# 1. IMPORTING MANDATORY LIBRARIES (pandas, matplotlib, sklearn)\n",
    "# ------------------------------------------------------------------------------\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt  # Standard visual engineering engine\n",
    "\n",
    "# Importing explicit Scikit-Learn functions required by the assignment rubric\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# 2. DATA LOADING & INSPECTION (Using pandas)\n",
    "# ------------------------------------------------------------------------------\n",
    "try:\n",
    "    # Read the core healthcare disease data repository file\n",
    "    df = pd.read_csv('framingham.csv')\n",
    "    print(\"🏥 Dataset loaded successfully via pandas!\")\n",
    "    print(f\"Dataset Dimensions: {df.shape[0]} rows, {df.shape[1]} columns\\n\")\n",
    "except FileNotFoundError:\n",
    "    print(\"❌ Error: 'framingham.csv' not found in the working directory.\")\n",
    "    print(\"Please ensure the dataset file sits alongside main.py.\")\n",
    "    exit()\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# 3. DATA PREPROCESSING (Handling missing clinical data and feature scaling)\n",
    "# ------------------------------------------------------------------------------\n",
    "print(\"--- Step 1: Preprocessing Data ---\")\n",
    "\n",
    "# Real-world clinical records contain empty cells. \n",
    "# We impute missing metrics using the column median to protect clinical integrity.\n",
    "imputer = SimpleImputer(strategy='median')\n",
    "df_clean = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)\n",
    "\n",
    "# Separate features (X) and the target disease variable (y)\n",
    "# TenYearCHD: 1 = Developed Coronary Heart Disease, 0 = Did not develop disease\n",
    "X = df_clean.drop(columns=['TenYearCHD'])\n",
    "y = df_clean['TenYearCHD']\n",
    "\n",
    "# Scale features to put metrics like age, cholesterol, and blood pressure on the same scale\n",
    "scaler = StandardScaler()\n",
    "X_scaled = scaler.fit_transform(X)\n",
    "print(\"✅ Clinical missing values handled and features scaled accurately.\\n\")\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# 4. TRAINING AND TESTING SPLIT (Using train_test_split)\n",
    "# ------------------------------------------------------------------------------\n",
    "print(\"--- Step 2: Executing Train-Test Split ---\")\n",
    "\n",
    "# Stratified split partitions 80% for training and 20% for testing, \n",
    "# while maintaining the target distribution ratio to protect against class imbalance bias.\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X_scaled, y, test_size=0.2, random_state=42, stratify=y\n",
    ")\n",
    "print(f\"Training Data Split Shape: {X_train.shape}\")\n",
    "print(f\"Testing Data Split Shape:  {X_test.shape}\\n\")\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# 5. MODEL TRAINING (Using correct ML model and fit method)\n",
    "# ------------------------------------------------------------------------------\n",
    "print(\"--- Step 3: Initializing & Fitting Machine Learning Model ---\")\n",
    "\n",
    "# Initialize Logistic Regression with balanced weighting to prioritize high-risk patient recall\n",
    "model = LogisticRegression(class_weight='balanced', random_state=42)\n",
    "\n",
    "# Train the model using the mandatory fit() method\n",
    "model.fit(X_train, y_train)\n",
    "print(\"🎯 Model training completed successfully via model.fit()!\\n\")\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# 6. MODEL PERFORMANCE TESTING & EVALUATION (Using predict and accuracy_score)\n",
    "# ------------------------------------------------------------------------------\n",
    "print(\"--- Step 4: Model Evaluation ---\")\n",
    "\n",
    "# Generate predictions on unseen test split using the mandatory predict() method\n",
    "y_pred = model.predict(X_test)\n",
    "\n",
    "# Calculate final accuracy metrics utilizing the required accuracy_score() function\n",
    "accuracy = accuracy_score(y_test, y_pred)\n",
    "\n",
    "print(\"====================================================\")\n",
    "print(\"            ASSIGNMENT EVALUATION REPORT            \")\n",
    "print(\"====================================================\")\n",
    "print(f\"🟢 Final Model Accuracy Score: {accuracy:.4f} ({accuracy * 100:.2f}%)\")\n",
    "print(\"\\nDetailed Classification Matrix Profile:\")\n",
    "print(classification_report(y_test, y_pred))\n",
    "print(\"====================================================\\n\")\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# 7. MANDATORY VISUALIZATION (Confusion Matrix via Modern Sklearn Display)\n",
    "# ------------------------------------------------------------------------------\n",
    "print(\"--- Step 5: Generating Performance Visualizations ---\")\n",
    "\n",
    "# Compute the classification grid data\n",
    "cm = confusion_matrix(y_test, y_pred)\n",
    "\n",
    "# Build a clean, professional visualization layout entirely bypassing old seaborn bugs\n",
    "disp = ConfusionMatrixDisplay(\n",
    "    confusion_matrix=cm, \n",
    "    display_labels=['Healthy (0)', 'At Risk (1)']\n",
    ")\n",
    "\n",
    "# Plot using the standard 'Blues' color palette matching your assignment requirements\n",
    "fig, ax = plt.subplots(figsize=(6, 5))\n",
    "disp.plot(cmap='Blues', ax=ax, colorbar=False, values_format='d')\n",
    "\n",
    "# Add clinical text elements and structural formatting constraints\n",
    "plt.title('Clinical Confusion Matrix Visualizer', fontsize=12, fontweight='bold', pad=15)\n",
    "plt.xlabel('Predicted Medical Diagnosis', fontsize=10, labelpad=10)\n",
    "plt.ylabel('Actual Clinical Assessment', fontsize=10, labelpad=10)\n",
    "plt.tight_layout()\n",
    "\n",
    "# Save the plot securely to fulfill assignment file requirements\n",
    "plt.savefig('visualization_screenshot.png', dpi=300)\n",
    "print(\"💾 Heatmap chart saved successfully as 'visualization_screenshot.png'!\")\n",
    "\n",
    "# Display the final chart window cleanly on your screen\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab8aacb7-d00e-4b09-9b8e-f26f7a5076c8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.21"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
