# -*- coding: utf-8 -*-
"""app_csv.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fg91m4y4devA1EXVce3dR3rhdxuJpPCO
"""

import gradio as gr
import tensorflow as tf
import joblib
import numpy as np
import pandas as pd

# 1. Model aur Scaler load karo
model = tf.keras.models.load_model("mlp_cancer_model.h5")
scaler = joblib.load("scaler.pkl")

feature_names = [
'mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness',
'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension',
'radius error', 'texture error', 'perimeter error', 'area error', 'smoothness error',
'compactness error', 'concavity error', 'concave points error', 'symmetry error', 'fractal dimension error',
'worst radius', 'worst texture', 'worst perimeter', 'worst area', 'worst smoothness',
'worst compactness', 'worst concavity', 'worst concave points', 'worst symmetry', 'worst fractal dimension'
]

# 2. Prediction function
def predict_csv(csv_file):
    if csv_file is None:
        return None, "❌ Please upload a CSV file"

    try:
        # CSV read karo
        df = pd.read_csv(csv_file.name)

        # Check: 30 columns hain?
        if df.shape[1]!= 30:
            return None, f"❌ Error: CSV me 30 columns hone chahiye. Tumhari CSV me {df.shape[1]} hain"

        df.columns = feature_names # column names set

        # Scale + Predict
        X = df.values
        X_scaled = scaler.transform(X)
        probs = model.predict(X_scaled, verbose=0).flatten()

        # Result add karo
        df['Malignant_Probability'] = np.round(probs, 4)
        df['Prediction'] = np.where(probs > 0.5, 'Malignant 🚨', 'Benign ✅')

        # Nayi CSV save karo
        output_path = "predictions_output.csv"
        df.to_csv(output_path, index=False)

        summary = f"Total Patients: {len(df)}\nBenign: {sum(probs<0.5)}\nMalignant: {sum(probs>0.5)}"

        return output_path, summary

    except Exception as e:
        return None, f"❌ Error: {str(e)}"

# 3. Gradio UI
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 📊 Breast Cancer Batch Prediction")
    gr.Markdown("CSV upload karo jisme 30 features hon. Prediction wali CSV download karlo.")

    with gr.Row():
        csv_input = gr.File(label="1. Upload CSV", file_types=[".csv"])

    btn = gr.Button("2. Predict All", variant="primary")

    with gr.Row():
        csv_output = gr.File(label="3. Download Predictions CSV")
        summary_box = gr.Textbox(label="Summary", lines=4)

    btn.click(fn=predict_csv, inputs=csv_input, outputs=[csv_output, summary_box])

    gr.Markdown("### Sample CSV")
    gr.Markdown("Is format me 30 columns hone chahiye. Har row = 1 patient")

demo.launch(share=True)